---
version: "2.1"
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - /mnt:/mnt
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  default:
    name: multimedia
    external: true
