---
version: "2.1"

services:
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
      - /mnt:/mnt
    ports:
      - 6767:6767
    restart: unless-stopped

networks:
  default:
    name: multimedia
    external: true
