version: '2'
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: always
    environment:
      - API_KEY={{CLOUDFLARE_API_KEY}}
      - ZONE={{MY_DOMAIN}}
      - PROXIED=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
