---
version: '3'

services:
  app:
    image: jc21/nginx-proxy-manager
    restart: unless-stopped
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    ports:
      - 80:80
      - 443:443
      - 8083:81
    volumes:
      - ./config:/data
      - ./letsencrypt:/etc/letsencrypt
