---
version: "2.1"
services:
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ./config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

networks:
  default:
    name: multimedia
    external: true

